### ISSUE TITLE
Use Animation error

### ISSUE THREAD

**Issue by SpastikChuwawa** [bblanimation/bricker#10]
Please copy the following form and paste it into a new issue at https://github.com/bblanimation/rebrickr/issues

Don't forget to include a description of your problem! The more information you provide (what you were trying to do, what action directly preceeded the error, etc.), the easier it will be for us to squash the bug.

### COPY EVERYTHING BELOW THIS LINE ###

Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1.5.1
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17134
   version  = 10.0.17134
   python   = 3.5.3
Error:
EXCEPTION (<class 'UnboundLocalError'>): local variable 'cache_frames' referenced before assignment
         C:\Users\James Morr\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-5-1\functions\point_cache.py
000 0084:getCachedFrames() return cache_frames
001 0037:getFirstUncachedFrame() cache_frames = getCachedFrames(obj, point_cache)
         C:\Users\James Morr\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-5-1\buttons\brickify.py
002 0669:getDuplicateObjects() firstUncachedFrame = getFirstUncachedFrame(self.source, point_cache)
003 0369:brickifyAnimation() duplicates = self.getDuplicateObjects(scn, cm, cm.source_name, cm.startFrame, cm.stopFrame)
004 0169:runBrickify() self.brickifyAnimation(scn, cm, n, matrixDirty)
         C:\Users\James Morr\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-5-1\functions\wrappers.py
005 0037:wrapped() ret = fn(*args, **kwargs)
         C:\Users\James Morr\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-5-1\buttons\brickify.py
006 0089:execute() self.runBrickify(context)

EXCEPTION (<class 'UnboundLocalError'>): local variable 'cache_frames' referenced before assignment
         C:\Users\James Morr\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-5-1\functions\point_cache.py
000 0084:getCachedFrames() return cache_frames
001 0037:getFirstUncachedFrame() cache_frames = getCachedFrames(obj, point_cache)
         C:\Users\James Morr\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-5-1\buttons\brickify.py
002 0669:getDuplicateObjects() firstUncachedFrame = getFirstUncachedFrame(self.source, point_cache)
003 0369:brickifyAnimation() duplicates = self.getDuplicateObjects(scn, cm, cm.source_name, cm.startFrame, cm.stopFrame)
004 0169:runBrickify() self.brickifyAnimation(scn, cm, n, matrixDirty)
         C:\Users\James Morr\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-5-1\functions\wrappers.py
005 0037:wrapped() ret = fn(*args, **kwargs)
         C:\Users\James Morr\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-5-1\buttons\brickify.py
006 0089:execute() self.runBrickify(context)

**Comment by bblanimation** [comment]
Thanks for reporting this issue! I have fixed the issue for the next version of Bricker (v1.5.2) which will be released shortly.
