### ISSUE TITLE
Brickify error

### ISSUE THREAD

**Issue by ParallelMayhem** [bblanimation/bricker#11]
Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1.5.1
Platform Info:
   system   = Darwin
   platform = Darwin-17.6.0-x86_64-i386-64bit
   version  = Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
   python   = 3.5.3
Error:
EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'y'
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/lib/bricksDict/functions.py
000 0141:getPixel() pixelNumber = (image_size_x * int(uv_coord.y)) + int(uv_coord.x)
001 0275:getUVPixelColor() rgba = getPixel(uv_images[image.name], uv_coord)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/lib/bricksDict/generate.py
002 0657:makeBricksDict() rgba = smokeColors[x][y][z] if smokeColors else getUVPixelColor(scn, source, nf, ni if ni is None else Vector(ni), uv_images, uvImageName)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/functions/wrappers.py
003 0037:wrapped() ret = fn(*args, **kwargs)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/lib/bricksDict/storage.py
004 0058:getBricksDict() bricksDict = makeBricksDict(source, source_details, brickScale, origSource=origSource, cursorStatus=updateCursor)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/buttons/brickify.py
005 0452:createNewBricks() bricksDict, loadedFromCache = getBricksDict(dType=action, source=source, source_details=source_details, dimensions=dimensions, brickScale=brickScale2, updateCursor=updateCursor, curFrame=curFrame, origSource=origSource, restrictContext=False)
006 0289:brickifyModel() group_name = self.createNewBricks(sourceDup, parent, sourceDup_details, dimensions, refLogo, logo_details, self.action, split=cm.splitModel, curFrame=None, sceneCurFrame=None, origSource=self.source)
007 0167:runBrickify() self.brickifyModel(scn, cm, n, matrixDirty, skipTransAndAnimData)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/functions/wrappers.py
008 0037:wrapped() ret = fn(*args, **kwargs)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/buttons/brickify.py
009 0089:execute() self.runBrickify(context)

EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'y'
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/lib/bricksDict/functions.py
000 0141:getPixel() pixelNumber = (image_size_x * int(uv_coord.y)) + int(uv_coord.x)
001 0275:getUVPixelColor() rgba = getPixel(uv_images[image.name], uv_coord)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/lib/bricksDict/generate.py
002 0657:makeBricksDict() rgba = smokeColors[x][y][z] if smokeColors else getUVPixelColor(scn, source, nf, ni if ni is None else Vector(ni), uv_images, uvImageName)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/functions/wrappers.py
003 0037:wrapped() ret = fn(*args, **kwargs)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/lib/bricksDict/storage.py
004 0058:getBricksDict() bricksDict = makeBricksDict(source, source_details, brickScale, origSource=origSource, cursorStatus=updateCursor)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/buttons/brickify.py
005 0452:createNewBricks() bricksDict, loadedFromCache = getBricksDict(dType=action, source=source, source_details=source_details, dimensions=dimensions, brickScale=brickScale2, updateCursor=updateCursor, curFrame=curFrame, origSource=origSource, restrictContext=False)
006 0289:brickifyModel() group_name = self.createNewBricks(sourceDup, parent, sourceDup_details, dimensions, refLogo, logo_details, self.action, split=cm.splitModel, curFrame=None, sceneCurFrame=None, origSource=self.source)
007 0167:runBrickify() self.brickifyModel(scn, cm, n, matrixDirty, skipTransAndAnimData)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/functions/wrappers.py
008 0037:wrapped() ret = fn(*args, **kwargs)
         /Users/cjmorsebrown/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-5-1/buttons/brickify.py
009 0089:execute() self.runBrickify(context)

**Comment by bblanimation** [comment]
Thank you for reporting this issue! In the next version of Bricker this issue will be handled gracefully.

For now – it looks like your model does not have an active UV layer. Have you verified that the model is unwrapped?

**Comment by ParallelMayhem** [comment]
Ah I didn't realise there had to be a UV map.
