### ISSUE TITLE
Object with hole does not fit cutout part

### ISSUE THREAD

**Issue by richardklingler** [bblanimation/bricker#13]
I did a small test with a logo which is based on a yellow disk and two letters...
The disk has a cutout formed of the two letters, and the two letters are moved to front for better visibility.

After running Bricker on all three objects the cutout of the disc doesn't reflect the cutout letters.
They letters should fit though in the cutouts Bricker generated.

![before_bricker](https://user-images.githubusercontent.com/11256235/48673618-874b5f00-eb43-11e8-80dd-47fe78237ae8.png)
![after_bricker_1](https://user-images.githubusercontent.com/11256235/48673620-8adee600-eb43-11e8-9cd3-3da533d56387.png)
![after_bricker_2](https://user-images.githubusercontent.com/11256235/48673621-8ca8a980-eb43-11e8-9187-863cb3a31276.png)
![after_bricker_3](https://user-images.githubusercontent.com/11256235/48673622-8f0b0380-eb43-11e8-80cb-47e24b1789bf.png)

**Comment by bblanimation** [comment]
Richard,

Thank you for reporting this! Actually, this is a setting that can be easily adjusted. The setting you're looking for is the "Model Settings > Brick Height", which determines the size of the bricks. You can manually set them to be the same size for each model, or you could select the model with the appropriate size, press the dropdown menu under the "Brick Models" tab, and press "Copy Settings to Others".

Hope this is helpful!

Christopher
