### ISSUE TITLE
register issue

### ISSUE THREAD

**Issue by ibrahhhh112** [bblanimation/bricker#23]
When I click the checkbox in blender's user preferences it says that the python in the init.py file defines no classes. Why is this?
<img width="835" alt="Screenshot 2019-03-14 at 10 19 13" src="https://user-images.githubusercontent.com/48550016/54349218-b0d44d00-4642-11e9-99b1-b012d7378ddc.png">

**Comment by bblanimation** [comment]
The newest version of Bricker (released today) should address this issue.
