### ISSUE TITLE
Cannot export to ldraw

### ISSUE THREAD

**Issue by minderella86** [bblanimation/bricker#24]
Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1, 6, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763
   version  = 10.0.17763
   python   = 3.5.3
Error:
EXCEPTION (<class 'TypeError'>): join() missing 1 required positional argument: 'path'
         C:\Users\ylem8\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-6-0\functions\general.py
000 0367:getExportPath() newPath = os.path.join(*splitPath)
         C:\Users\ylem8\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-6-0\buttons\exportLdraw.py
001 0064:writeLdrawFile() path, errorMsg = getExportPath(n, ".ldr", cm.exportPath, frame=frame, subfolder=cm.animated)
002 0049:execute() self.writeLdrawFile()

**Comment by bblanimation** [comment]
Thank you for reporting this issue! The issue has been fixed (with commit 4abe119), and an updated version of Bricker (v1.6.1) will be released later today.

**Comment by bblanimation** [comment]
New release has been posted (v1.6.1). Thanks again for reporting this issue – I hope you continue to enjoy Bricker and consider leaving a review on the Blender Market!

Best,
Christopher
