### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by minderella86** [bblanimation/bricker#25]
### COPY EVERYTHING BELOW THIS LINE ###

Description of the Problem:

Blender Version: 002.080.057
Addon Version: 1, 6, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.14393
   version  = 10.0.14393
   python   = 3.7.0
Error:
EXCEPTION (<class 'NameError'>): name 'lastSlash' is not defined
         C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\bricker_v1-6-0\functions\general.py
000 0377:getExportPath() fn0 = fn if lastSlash in (-1, len(basePath) - 1) else basePath[lastSlash + 1:]
         C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\bricker_v1-6-0\buttons\exportLdraw.py
001 0064:writeLdrawFile() path, errorMsg = getExportPath(n, ".ldr", cm.exportPath, frame=frame, subfolder=cm.animated)
002 0049:execute() self.writeLdrawFile()

**Comment by bblanimation** [comment]
Thank you for reporting this issue! This was solved in a recent version of Bricker (v1.6.1) – you can download the new version directly from the Blender Market via the 'Orders' page. If you run into further issues, please feel free to report them here or shoot me an email (chris@bblanimation.com).
