### ISSUE TITLE
cannot brickify

### ISSUE THREAD

**Issue by minderella86** [bblanimation/bricker#26]
Blender Version: 002.079.000
Addon Version: 1, 6, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763
   version  = 10.0.17763
   python   = 3.5.3
Error:
EXCEPTION (<class 'TypeError'>): object of type 'NoneType' has no len()
         C:\Users\ylem8\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-6-0\lib\background_processing\classes\JobManager.py
000 0308:get_issue_string() errormsg += "[stderr]\n" if len(stderr) > 0 else "[stdout]\n"
         C:\Users\ylem8\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-6-0\buttons\brickify.py
001 0121:modal() errormsg = self.JobManager.get_issue_string(job)

**Comment by bblanimation** [comment]
Thank you for reporting this issue! If this issue persists once you've updated to Bricker v1.6.1, please leave an additional comment here and we can begin troubleshooting the issue.
