### ISSUE TITLE
Bricker fails to activate on reloading Blender when "Brickify in Background" is disabled

### ISSUE THREAD

**Issue by arnoldemu** [bblanimation/bricker#27]
Hi,
I am using Windows 10 and Blender 2.8 8f1951f555f5. Bricker 1.6.3

- Load Blender.
- Create a cube.
- Brickify it
- In Bricker add-on options turn off "Brickify in background".
- Close Blender
- Re-open blender

Bricker will fail to activate and give a script error because "brickifyinbackground" can't be found. Workaround is to delete pycache.

**Comment by arnoldemu** [comment]
I saw this again.

"update_undo_state_in_background" is undefined. timers.py around line 171.

**Comment by bblanimation** [comment]
Thank you for the additional information! I found the source of this issue
and I'll release an updated version of Bricker soon.
