### ISSUE TITLE
Misaligned and invalid positions in LDR export of 'Slopes' brick type

### ISSUE THREAD

**Issue by arnoldemu** [bblanimation/bricker#28]
Hello,
I am using Windows 10. Blender 2.8. Bricker 1.6.3

When using 'slopes' brickify option exported LDR file will have blocks in invalid positions. Will give warning on import into Lego Designer

- Load Blender
- Create an organic shape. (Something which is smooth and is 'blobby' in appearance)
- Brickify it with 'slopes' method.
- Export to LDR.
- Import into Lego Designer. Notice how Lego Designer reports a lot of bricks are misaligned. You can also see this when you rotate the view.

If 'slopes' is not used, the export will be fine.

**Comment by bblanimation** [comment]
Thanks for reporting this issue! The 'Slopes' method is still in development and should not be available in the interface yet – did you download Bricker from the Blender Market?

**Comment by arnoldemu** [comment]
Yes I got Bricker from the Blender Market. I had issues exporting LDR files and so I downloaded the GitHub head version over the top to try that.

**Comment by bblanimation** [comment]
Ah, that explains it. I hope to have the 'Slopes' feature fully functioning in the near future, although it's not the top priority at the moment. Thanks for reporting this issue – I'll be sure that the LDR exporter can handle these slopes when the feature is complete.
