### ISSUE TITLE
LD Export directory picker doesn't seem to update text box next to it.

### ISSUE THREAD

**Issue by arnoldemu** [bblanimation/bricker#29]
Hi,
I am using Windows 10. Blender 2.8. Bricker 1.6.3 

Load Blender.
Create a cube
In the bricker UI, use the button to pick a directory.
It seems that the text box next to it is not updated and remains as the default.
In addition it seems that for most reliable option I need to manually type the directory into the textbox.

**Comment by bblanimation** [comment]
Thank you for reporting this issue! The UI for LDraw exporting has been redesigned in Bricker v1.7, and this should no longer be an issue.
