### ISSUE TITLE
LDExport can fail if you reload after brickifying

### ISSUE THREAD

**Issue by arnoldemu** [bblanimation/bricker#30]
Hi,
I am using Windows 10, Blender 2.8 and Bricker 1.6.3

load blender
Create a cube
brickify it
save the scene
reload blender
Now try to export to LDraw. It will fail here:

 offset = vec_conv(bricksDict[list(bricksDict.keys())[0]]["co"], int)

bricksDict is "NoneType".

**Comment by bblanimation** [comment]
Thank you for reporting this issue! The issue has been fixed in Bricker v1.7.
