### ISSUE TITLE
Brickify error

### ISSUE THREAD

**Issue by eugenelwc** [bblanimation/bricker#33]
Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1, 6, 2
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763
   version  = 10.0.17763
   python   = 3.5.3
Error:
EXCEPTION (<class 'json.decoder.JSONDecodeError'>): Expecting value: line 1 column 388994424 (char 388994423)
         C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py
000 0357:raw_decode() raise JSONDecodeError("Expecting value", s, err.value) from None
001 0339:decode() obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py
002 0319:loads() return _default_decoder.decode(s)
         C:\Users\eugen\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-6-2\buttons\brickify.py
003 0076:modal() bricksDict = None if retrieved_data["bricksDict"] in ("", "null") else json.loads(retrieved_data["bricksDict"])

**Comment by bblanimation** [comment]
Hi Eugene – thanks for reporting this error! This issue was addressed in the latest release of Bricker (v1.6.3) – you can install it from the Blender Market. Let me know if this doesn't solve the issue and I'd be happy to look into it further.

**Comment by bblanimation** [comment]
Hi Eugene – thanks for reporting this issue! I'll work on a fix for this right away. In the mean time, you can get around this issue by disabling the background processor in the Bricker Addon Preferences (File > User Preferences > Addons > Bricker > Brickify in Background > Off).

**Comment by bblanimation** [comment]
As this error has not been reported since the release of Bricker v1.7, it is safe to assume this issue has been taken care of with the bug fixes that came with that release.
