### ISSUE TITLE
Brickify error

### ISSUE THREAD

**Issue by eugenelwc** [bblanimation/bricker#34]
Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1, 6, 2
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763
   version  = 10.0.17763
   python   = 3.5.3
Error:

------ ISSUE WITH BACKGROUND PROCESSOR ------

[stdout]

---------------------------------------------

**Comment by bblanimation** [comment]
Hi Eugene, thanks for reporting this! Try updating to Bricker v1.6.3, and if the issue persists, feel free to open another issue here on github.
