### ISSUE TITLE
bricker doesn't always ask you to save the scene

### ISSUE THREAD

**Issue by arnoldemu** [bblanimation/bricker#35]
Hi,
I am using Windows 10, Blender 2.8 and bricker 1.6.3.

This is a minor issue.  If a model has already been brickified then bricker will not ask you to save the scene.

New scene/file
Import geometry (I imported from Collada)
Brickify it using default settings.
It should ask you to save the scene. Go ahead and do that and brickify the geometry.
New scene/file
import the same geometry 
Brickify it using default settings
It will not ask you to save the scene.
Change settings in bricker and re-brickify it. Now it will ask you to save the scene.

**Comment by bblanimation** [comment]
Hi,

Thank you for reporting this! This is actually performing as expected - Bricker only prompts you to save the scene before brickifying if the background processor is being used (see Blender > Preferences > Addons > Bricker > Brickify in Background). In some cases, Bricker doesn’t need to use the background processor, so you can brickify the model without saving.

Hope this is helpful!

Christopher
