### ISSUE TITLE
'brickify' button immediately leads to error

### ISSUE THREAD

**Issue by wtfreely** [bblanimation/bricker#36]
Description of the Problem:
Installed a new May 21 build of the Blender 2.80 beta and it seems to have flubbed the addon which was working prior.  Happens as soon as I try to brickify anything, even a basic cube.

There are some other recent posts on the blender git regarding this:
https://developer.blender.org/T64792

Thanks for your hard work guys <3

Blender Version: 002.080.071
Addon Version: 1, 6, 2
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763
   version  = 10.0.17763
   python   = 3.7.0
Error:
EXCEPTION (<class 'AttributeError'>): 'Context' object has no attribute 'depsgraph'
         C:\Users\wjtem\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\bricker_v1-6-2\buttons\brickify.py
000 0802:isValid() if bpy.context.depsgraph.objects.get(source.name) is None:
001 0283:runBrickify() if not self.isValid(scn, cm, n, self.source):
002 0199:execute() success = self.runBrickify(context)

**Comment by bblanimation** [comment]
Thanks for reporting this issue! This error is caused by a few minor changes in the Blender API – I'm going to hold off on releasing a new version of Bricker until the API is a bit more stable after the UI freeze. Until then, I would keep an older build of Blender 2.80 around for use with Bricker.
