### ISSUE TITLE
Run Brickify bricks and plates

### ISSUE THREAD

**Issue by mjsweet130** [bblanimation/bricker#39]
Please copy the following form and paste it into a new issue at https://github.com/bblanimation/bricker/issues

Don't forget to include a description of your problem! The more information you provide (what you were trying to do, what action directly preceeded the error, etc.), the easier it will be for us to squash the bug.

### COPY EVERYTHING BELOW THIS LINE ###

Description of the Problem:

Blender Version: 002.080.074
Addon Version: 1, 6, 3
Platform Info:
   system   = Darwin
   platform = Darwin-18.6.0-x86_64-i386-64bit
   version  = Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
   python   = 3.7.0
Error:
EXCEPTION (<class 'KeyError'>): 'omnomScan.jpg'
         /Users/msweet/Library/Application Support/Blender/2.80/scripts/addons/bricker_v1-6-3/lib/bricksDict/functions.py
000 0346:getUVPixelColor() rgba = getPixel(uv_images[image.name], uv_coord)
001 0387:getBrickRGBA() rgba = getUVPixelColor(scn, obj, face_idx, point, uv_images, image)
         /Users/msweet/Library/Application Support/Blender/2.80/scripts/addons/bricker_v1-6-3/lib/bricksDict/modify.py
002 0072:updateMaterials() rgba, matName = getBrickRGBA(scn, source, nf, ni, uv_images, uvImage)
         /Users/msweet/Library/Application Support/Blender/2.80/scripts/addons/bricker_v1-6-3/buttons/brickify.py
003 0750:createNewBricks() if cm.materialType != "NONE" and (cm.materialIsDirty or cm.matrixIsDirty or cm.animIsDirty): bricksDict = updateMaterials(bricksDict, source, uv_images, keys, curFrame)
004 0649:brickifyActiveFrame() coll_name, _ = BRICKER_OT_brickify.createNewBricks(sourceDup, parent, sourceDup_details, dimensions, refLogo, logo_details, action, split=cm.splitModel, curFrame=None)
005 0466:brickifyModel() bColl = self.brickifyActiveFrame(self.action)
006 0333:runBrickify() self.brickifyModel(scn, cm, n, matrixDirty)
007 0199:execute() success = self.runBrickify(context)

**Comment by mjsweet130** [comment]
Loaded .obj into Blender 2.8
Imported ABS materials, applied bright green.
Changed brick types from bricks to bricks and plates.
Crash

**Comment by bblanimation** [comment]
Do you happen to have the blend file accessible from which you got this error?

**Comment by bblanimation** [comment]
I am closing this task due to a lack of necessary information.
