### ISSUE TITLE
Export to Ldraw File leads to error

### ISSUE THREAD

**Issue by marboeck** [bblanimation/bricker#42]
I brickified a model using the addon Bricker_v1-6-3 in Blender 2.8. with default settings . 
An Export to Ldraw Format leads to an error (same with a Default cube):

EXCEPTION (<class 'AttributeError'>): module 'bpy.props' has no attribute 'abs_mat_properties'
         C:\Users\marboeck\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\bricker_v1-6-3\functions\colors.py
000 0030:getColors() mat_properties = bpy.props.abs_mat_properties
001 0040:findNearestBrickColorName() colors = getColors().copy()
         C:\Users\marboeck\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\bricker_v1-6-3\buttons\exportLdraw.py
002 0118:writeLdrawFile() mat_name = findNearestBrickColorName(rgba, transWeight)
003 0048:execute() self.writeLdrawFile()

----------------------------------------------------------------------------------------------------
Something went wrong. Please start an error report with us so we can fix it! ('Bricker > Brick Models > Report Error')
----------------------------------------------------------------------------------------------------

We want to build a  model for a Exhibition using the addon brickify and legodesigner for generating a list of parts (for purchase) and a manual. 
Can you please help us out? Thank you

**Comment by Khuppe** [comment]
I'm having the same problem as well

**Comment by bblanimation** [comment]
Hi,

Thank you for reporting this issue! This was fixed in the most recent release of Bricker (v1.7.0) - you can find the download link on the Blender Market under your 'Orders' page.
