### ISSUE TITLE
Smoke Brickifying Failing

### ISSUE THREAD

**Issue by ParallelMayhem** [bblanimation/bricker#44]
Description of the Problem:

Blender Version: 002.081.016
Addon Version: 1, 6, 2
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.18362
   version  = 10.0.18362
   python   = 3.7.4
Error:

------ ISSUE WITH BACKGROUND PROCESSOR ------

[stdout]

---------------------------------------------

This happens when I set the background processes to 'Off' and when they're on 'On' blender immediately quits.

**Comment by bblanimation** [comment]
Hi Sam,

Thank you for sending this error report over. It looks like you’re using an outdated version of Bricker - you’ll find a download link to 1.7.2 on your orders page on Blender Market - give that a try and let me know if that fixes your issue.

Hope you’re enjoying Bricker!

Best,

Christopher
