### ISSUE TITLE
Bricker Copy Paste Fail

### ISSUE THREAD

**Issue by sonarburn** [bblanimation/bricker#45]
Description of the Problem: Copy and Paste settings for Bricker doesn't work. No way to save or transfer the settings from one model to the next.

Blender Version: 002.081.016
Addon Version: 1, 7, 3
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.18362
   version  = 10.0.18362
   python   = 3.7.4
Error:
EXCEPTION (<class 'TypeError'>): IDMaterials.clear(): takes at most 0 arguments, got 1
         C:\Users\ncdod\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\bricker_v1-7-3_beta\functions\cmlist_utils.py
000 0153:match_properties() mat_obj_to.data.materials.clear(update_data=True)
         C:\Users\ncdod\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\bricker_v1-7-3_beta\operators\cmlist_actions.py
001 0239:execute() match_properties(cm0, cm1)

**Comment by bblanimation** [comment]
This issue has been addressed in the latest commit, and will be fixed in the next release of Bricker.

**Comment by sonarburn** [comment]
Thanks Chris

I tried the beta but had no luck and other issues so I went back to the
current stable build for the rest of the project and just typed stuff in
manually.

Cheers,
Nathan Dodge
Creative Art Director | Motion Designer | Animator
www.nathanaeldodge.com
