### ISSUE TITLE
Smoke simulations not working

### ISSUE THREAD

**Issue by moldywings** [bblanimation/bricker#60]
Whenever I try and brickify a smoke simulation animation, it doesn't do anything and gives me an error

Description of the Problem:

Blender Version: 002.082.007
Addon Version: 1, 7, 3
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.18362-SP0
   version  = 10.0.18362
   python   = 3.7.4
Error:
EXCEPTION (<class 'TypeError'>): 'NoneType' object is not subscriptable
         C:\Users\moldy\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bricker_v1-8-0\functions\bricksdict\generate.py
000 0392:get_brick_matrix_smoke() xn0 = domain_res[0] / d.x
001 0651:make_bricksdict() brick_freq_matrix, smoke_colors = get_brick_matrix_smoke(cm, source, face_idx_matrix, cm.brick_shell, source_details, cursor_status=cursor_status)
         C:\Users\moldy\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bricker_v1-8-0\functions\common\wrappers.py
002 0033:wrapped() ret = fn(*args, **kwargs)
         C:\Users\moldy\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bricker_v1-8-0\functions\brickify_utils.py
003 0228:get_bricksdict_for_model() bricksdict = make_bricksdict(source, source_details, brick_scale2, cursor_status=update_cursor)
004 0267:create_new_bricks() bricksdict, brick_scale = get_bricksdict_for_model(cm, source, source_details, action, cur_frame, brick_scale, bricksdict, keys, redraw, update_cursor)
         C:\Users\moldy\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bricker_v1-8-0\operators\brickify.py
005 0609:brickify_current_frame() coll_name, _ = create_new_bricks(source, parent, source_details, dimensions, action, split=cm.split_model, cur_frame=cur_frame, clear_existing_collection=False, orig_source=cm.source_obj, select_created=False)
006 0561:brickify_animation() success = self.brickify_current_frame(cur_frame, self.action)
007 0319:run_brickify() self.brickify_animation(scn, cm, n, matrix_dirty)
008 0188:execute() success = self.run_brickify(context)

**Comment by bblanimation** [comment]
This issue has been resolved – new release coming later this week!
