### ISSUE TITLE
Mysterious update that can't be installed.

### ISSUE THREAD

**Issue by webdogk9** [bblanimation/bricker#62]
When trying to update via the updater I get two things :
The first is the plugin updates and asks for a restart of blender.

The second time it fails claiming there's an extraction error. 
![Capture_2](https://user-images.githubusercontent.com/16289488/75994224-bd863b00-5f4e-11ea-9c3b-8ac66d76aada.PNG)

 The manual install also fails to link, it just goes to the store page.

![Capture](https://user-images.githubusercontent.com/16289488/75993853-3933b800-5f4e-11ea-8e2d-e4a0f68f1655.PNG)

**Comment by bblanimation** [comment]
Thank you for reporting this bug! It looks like this was a known issue for the addon updater which was recently fixed: https://github.com/CGCookie/blender-addon-updater/commit/d1719205e59066fa3616a7c72da34a7523e443d5

This has now been implemented into Bricker for the next release.
