### ISSUE TITLE
Exporting to Ldraw fails - better feedback required.

### ISSUE THREAD

**Issue by webdogk9** [bblanimation/bricker#64]
Description of the Problem:
Exporting out a brick model fails.  Possible reason was because the model mesh hasn't been updated?

Blender Version: 002.082.007
Addon Version: 1, 8, 1
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.18362-SP0
   version  = 10.0.18362
   python   = 3.7.4
Error:
EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'keys'
         C:\Users\UseraAme\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bblanimation-bricker-c070b52\operators\export_ldraw.py
000 0094:write_ldraw_file() offset = vec_conv(bricksdict[list(bricksdict.keys())[0]]["co"], int)
001 0047:execute() self.write_ldraw_file()

**Comment by bblanimation** [comment]
Thank you for reporting this bug! This issue is now fixed by commit dfcc5ddb921a2f2ade0f766f59f66230f71c3be2, and the improved feedback for this error will be available in the next release.
