### ISSUE TITLE
Error trying to apply a texture

### ISSUE THREAD

**Issue by MardyMarvin** [bblanimation/bricker#69]
I had created a model and bricked it. I then went to the material drop down and selected use single material and went to select one of the ABS plastic materials. The previews were missing but I ignored that and carried on. Then I selected one from the drop down then I clicked apply material and this is when the error appreared.

My models before the bricking has a material assigned not sure if this is an issue or not.

Please copy the following form and paste it into a new issue at https://github.com/bblanimation/bricker/issues

Don't forget to include a description of your problem! The more information you provide (what you were trying to do, what action directly preceeded the error, etc.), the easier it will be for us to squash the bug.

### COPY EVERYTHING BELOW THIS LINE ###

Description of the Problem:

Blender Version: 002.082.007
Addon Version: 2, 0, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.18362-SP0
   version  = 10.0.18362
   python   = 3.7.4
Error:
EXCEPTION (<class 'NameError'>): name 'select' is not defined
         C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bricker_v2-0-0\functions\common\materials.py
000 0034:clear_existing_materials() select(obj, active=True)
         C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bricker_v2-0-0\operators\apply_material.py
001 0119:run_apply_material() clear_existing_materials(brick, from_idx=1)
         C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bricker_v2-0-0\functions\common\wrappers.py
002 0033:wrapped() ret = fn(*args, **kwargs)
         C:\Users\ \AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\bricker_v2-0-0\operators\apply_material.py
003 0054:execute() self.run_apply_material(context)

**Comment by MardyMarvin** [comment]
It looks like the item had a blank material and this is what was causing the error as soon as I deleted it then it would apply all correctly

![image](https://user-images.githubusercontent.com/64381394/80320556-051e9a00-880f-11ea-8013-4aa3bf896350.png)

**Comment by bblanimation** [comment]
Thank you for reporting this issue! A fix has been implemented and will be coming in the next Bricker release to ensure the error won't pop up.
