### ISSUE TITLE
Bricker issue on Mac Pro 2013 in Blender 2.82b

### ISSUE THREAD

**Issue by swinz98** [bblanimation/bricker#70]
Description of the Problem:

Blender Version: 002.082.007
Addon Version: 2, 0, 0
Platform Info:
   system   = Darwin
   platform = Darwin-18.7.0-x86_64-i386-64bit
   version  = Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64
   python   = 3.7.4
Error:

------ ISSUE WITH BACKGROUND PROCESSOR ------

[stderr]
Traceback (most recent call last):
  File "/tmp/background_processing/brickify_in_background_template_lego test__Sphere.py", line 56, in <module>
    bpy.ops.cmlist.list_action(action="ADD")
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.cmlist.list_action" error, could not be found

---------------------------------------------

**Comment by bblanimation** [comment]
Thank you for reporting this issue! It looks like Bricker did not install
correctly. Try removing the addon from Blender, redownloading the latest
build from the Blender Market, and re-installing the addon. Let me know if
this doesn't work, and I'll be happy to investigate further!

**Comment by bblanimation** [comment]
Assuming this is resolved; closing.
