### ISSUE TITLE
Custom Logo fails

### ISSUE THREAD

**Issue by jcappelletti108** [bblanimation/bricker#73]
It fails with this error every time I try to update after picking custom logo. I got it to work once, but it seemed like it failed before really finishing. The bricks were smooth shaded, not auto smooth, but the logo did end up in the correct spot. i tried to adjust and update and failed script. 

Maybe I missed something. The model is clean, reasonably low poly, Centered on world origin. Applied all transforms. I'm simply testing on a IsoSphere with default brickify settings. No other objects in an empty scene. 

Started over, deleting brickify objects, adding logo and got this straight fail. 

Description of the Problem:

Blender Version: 002.083.000
Addon Version: 2, 0, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763-SP0
   version  = 10.0.17763
   python   = 3.7.4
Error:
EXCEPTION (<class 'ReferenceError'>): StructRNA of type Object has been removed
         C:\Users\jc\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\functions\brickify_utils.py
000 0374:create_new_bricks() bpy.data.objects.remove(ref_logo)
         C:\Users\jc\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\operators\brickify.py
001 0634:brickify_active_frame() coll_name, _ = create_new_bricks(source_dup, parent, source_dup_details, dimensions, action, split=cm.split_model, cur_frame=None)
002 0445:brickify_model() bcoll = self.brickify_active_frame(self.action)
003 0326:run_brickify() self.brickify_model(scn, cm, n, matrix_dirty)
004 0188:execute() success = self.run_brickify(context)

**Comment by jcappelletti108** [comment]
started over again, new Torus default settings. custom logo applied, brick pips are soft shaded, custom logo is correct per brick, but the bricks are all exploded from where they should be. 

Description of the Problem:

Blender Version: 002.083.000
Addon Version: 2, 0, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763-SP0
   version  = 10.0.17763
   python   = 3.7.4
Error:
EXCEPTION (<class 'ReferenceError'>): StructRNA of type Object has been removed
         C:\Users\jc\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\functions\brickify_utils.py
000 0374:create_new_bricks() bpy.data.objects.remove(ref_logo)
         C:\Users\jc\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\operators\brickify.py
001 0634:brickify_active_frame() coll_name, _ = create_new_bricks(source_dup, parent, source_dup_details, dimensions, action, split=cm.split_model, cur_frame=None)
002 0445:brickify_model() bcoll = self.brickify_active_frame(self.action)
003 0326:run_brickify() self.brickify_model(scn, cm, n, matrix_dirty)
004 0188:execute() success = self.run_brickify(context)


Trying to update after this keeps throwing error:
Description of the Problem:

Blender Version: 002.083.000
Addon Version: 2, 0, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763-SP0
   version  = 10.0.17763
   python   = 3.7.4
Error:
EXCEPTION (<class 'ReferenceError'>): StructRNA of type Object has been removed
         C:\Users\jc\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\functions\brickify_utils.py
000 0374:create_new_bricks() bpy.data.objects.remove(ref_logo)
         C:\Users\jc\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\operators\brickify.py
001 0634:brickify_active_frame() coll_name, _ = create_new_bricks(source_dup, parent, source_dup_details, dimensions, action, split=cm.split_model, cur_frame=None)
002 0445:brickify_model() bcoll = self.brickify_active_frame(self.action)
003 0326:run_brickify() self.brickify_model(scn, cm, n, matrix_dirty)
004 0188:execute() success = self.run_brickify(context)

**Comment by bblanimation** [comment]
Hi JC – thanks for reporting this issue! I've just committed a fix for this and will send you an updated beta of Bricker via email in the interrim until the next version of Bricker is ready for release so that you can use the custom logo functionality! As for your second comment – please let me know if you run into this issue again after you try out the new Bricker version and I can look into that further.
