### ISSUE TITLE
Bricker not working with mantaflow fire/smoke sim

### ISSUE THREAD

**Issue by iNath15** [bblanimation/bricker#74]
Description of the Problem:

Blender Version: 002.083.000
Addon Version: 2, 1, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.18362-SP0
   version  = 10.0.18362
   python   = 3.7.4
Error:
EXCEPTION (<class 'TypeError'>): Object of type float32 is not JSON serializable
         C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\json\encoder.py
000 0179:default() raise TypeError(f'Object of type {o.__class__.__name__} '
001 0257:iterencode() return _iterencode(o, 0)
002 0199:encode() chunks = self.iterencode(o, _one_shot=True)
         C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\json\__init__.py
003 0231:dumps() return _default_encoder.encode(obj)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\smoke_sim.py
004 0050:store_smoke_data() to_obj.smoke_data = compress_str(json.dumps(smoke_data))
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\brickify_utils.py
005 0142:get_duplicate_objects() store_smoke_data(source, source_dup)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\operators\brickify.py
006 0521:brickify_animation() duplicates = get_duplicate_objects(scn, cm, self.action, cm.start_frame, cm.stop_frame, self.updated_frames_only)
007 0336:run_brickify() self.brickify_animation(scn, cm, n, matrix_dirty)
008 0194:execute() success = self.run_brickify(context)

**Comment by bblanimation** [comment]
Thank you for reporting this issue! I've resolved this and will release a new version soon! In the meantime, you can avoid this error by disabling the background processor in the addon preferences.
