### ISSUE TITLE
brickify issue

### ISSUE THREAD

**Issue by iNath15** [bblanimation/bricker#75]
Description of the Problem:

Blender Version: 002.083.002
Addon Version: 2, 1, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.19041-SP0
   version  = 10.0.19041
   python   = 3.7.4
Error:
EXCEPTION (<class 'IndexError'>): index 27173192 is out of bounds for axis 0 with size 27173192
         C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\site-packages\numpy\core\fromnumeric.py
000 0545:put() return put(ind, v, mode=mode)
         <__array_function__ internals>
001 0006:put() 
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\common\images\pixel_effects_median_cut.py
002 0046:median_cut_quantize() np.put(new_img_arr, ind_arr, color_ave)
003 0065:split_into_buckets() median_cut_quantize(new_img_arr, img_arr, channels)
004 0089:split_into_buckets() split_into_buckets(new_img_arr, img_arr[median_index:], depth - 1, channels)
005 0088:split_into_buckets() split_into_buckets(new_img_arr, img_arr[:median_index], depth - 1, channels)
006 0089:split_into_buckets() split_into_buckets(new_img_arr, img_arr[median_index:], depth - 1, channels)
007 0089:split_into_buckets() split_into_buckets(new_img_arr, img_arr[median_index:], depth - 1, channels)
008 0028:cluster_pixels() split_into_buckets(new_pix_2d, pix_2d_with_idxs, depth, channels)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\common\images\image_sampling.py
009 0055:get_pixels() pixels = cluster_pixels(pixels, color_depth, image.channels)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\common\wrappers.py
010 0067:callit() return fns[n](*args, **kwargs)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\common\images\image_sampling.py
011 0105:get_pixels_cache() pixels = get_pixels(image, color_depth=color_depth, blur_radius=blur_radius) if image.source in ("FILE", "GENERATED") else get_pixels_at_frame(image, frame)
012 0166:get_pixel() pixels = pixels or get_pixels_cache(image, frame=image_frame, color_depth=color_depth, blur_radius=blur_radius)
013 0193:get_uv_pixel_color() rgba = get_pixel(image, uv_coord, image_frame=image_frame, color_depth=color_depth, blur_radius=blur_radius)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\mat_utils.py
014 0247:get_brick_rgba() rgba = get_uv_pixel_color(obj, face_idx, point, image, color_depth=color_depth, blur_radius=blur_radius)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\bricksdict\modify.py
015 0069:update_materials() rgba, mat_name = get_brick_rgba(source_dup, nf, ni, uv_image, color_depth=color_depth, blur_radius=blur_radius)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\functions\brickify_utils.py
016 0295:get_bricksdict_for_model() bricksdict = update_materials(bricksdict, source, keys, cur_frame=cur_frame, action=action)
017 0337:create_new_bricks() bricksdict, brick_scale = get_bricksdict_for_model(cm, source_dup, source_details, action, cur_frame, brick_scale, bricksdict, keys, redrawing, update_cursor)
         C:\Users\Nathaniel\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker-master\operators\brickify.py
018 0652:brickify_active_frame() coll_name, _ = create_new_bricks(source_dup, parent, source_dup_details, dimensions, action, split=cm.split_model, cur_frame=None)
019 0454:brickify_model() bcoll = self.brickify_active_frame(self.action)
020 0335:run_brickify() self.brickify_model(scn, cm, n, matrix_dirty)
021 0195:execute() success = self.run_brickify(context)

**Comment by bblanimation** [comment]
Hi,

Thank you for reporting this issue! I haven't been able to recreate this for myself – would you mind sending over the Blend file where you ran into this issue? No worries if you don't have it handy - just keep this in mind so you can send over the Blend file you ever run into this issue again.

-Christopher

**Comment by bblanimation** [comment]
Closing this as I haven't heard back in a while.
