### ISSUE TITLE
Bricker Explosion Issue

### ISSUE THREAD

**Issue by galacticbricks** [bblanimation/bricker#76]
Description of the Problem:

Blender Version: 002.083.000
Addon Version: 2, 0, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.18362-SP0
   version  = 10.0.18362
   python   = 3.7.4
Error:
EXCEPTION (<class 'TypeError'>): Object of type float32 is not JSON serializable
         C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\json\encoder.py
000 0179:default() raise TypeError(f'Object of type {o.__class__.__name__} '
001 0257:iterencode() return _iterencode(o, 0)
002 0199:encode() chunks = self.iterencode(o, _one_shot=True)
         C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\json\__init__.py
003 0231:dumps() return _default_encoder.encode(obj)
         C:\Users\zacha\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\functions\smoke_sim.py
004 0050:store_smoke_data() to_obj.smoke_data = compress_str(json.dumps(smoke_data))
         C:\Users\zacha\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\functions\brickify_utils.py
005 0139:get_duplicate_objects() store_smoke_data(source, source_dup)
         C:\Users\zacha\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\bricker_v2-0-0\operators\brickify.py
006 0514:brickify_animation() duplicates = get_duplicate_objects(scn, cm, self.action, cm.start_frame, cm.stop_frame, self.updated_frames_only)
007 0328:run_brickify() self.brickify_animation(scn, cm, n, matrix_dirty)
008 0188:execute() success = self.run_brickify(context)

**Comment by bblanimation** [comment]
Thanks for reporting this issue! This issue has been fixed and will be included in the next release.
