### ISSUE TITLE
Mantaflow Simulation Error

### ISSUE THREAD

**Issue by yoop** [bblanimation/bricker#77]
When I try to brickify a baked mantaflow explosion simulation, I receive the error below. 
I have tried different computers, versions of blender and versions of bricker, but they all give the same error. The mantaflow simulation has been baked with and without noise several times. 

**Description of the Problem:**

Blender Version: 002.083.005
Addon Version: 2, 1, 0
Platform Info:
   system   = Linux
   platform = Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid
   version  = #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
   python   = 3.7.4
Error:
EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'children'
         /home/yoop/.config/blender/2.83/scripts/addons/bricker-master/functions/common/transform.py
000 0072:children_clear() for obj in parent.children:
         /home/yoop/.config/blender/2.83/scripts/addons/bricker-master/operators/brickify.py
001 0518:brickify_animation() children_clear(cm.parent_obj)  # clear children so they aren't sent to background processor
002 0340:run_brickify() self.brickify_animation(context, scn, cm, n, matrix_dirty)
003 0195:execute() success = self.run_brickify(context)

**Comment by bblanimation** [comment]
Thank you for the error report! I've resolved this and will include the fix in the next release.
