### ISSUE TITLE
Export to Ldraw - V2.22

### ISSUE THREAD

**Issue by RangaBricks** [bblanimation/bricker#78]
Exporting a bricker result results in this error.

Blender Version: 002.090.000
Addon Version: 2, 2, 0
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.19041-SP0
   version  = 10.0.19041
   python   = 3.7.7
Error:
EXCEPTION (<class 'NameError'>): name 'submodel_start_lines' is not defined
         C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\bricker_v2-1-0\operators\export_ldraw.py
000 0168:populate_filelines_layers() self.start_submodel(submodel_start_lines,  f"Layer {i + 1}")
001 0147:write_ldraw_file() self.populate_filelines_layers(bricksdict, p_keys_dict, sorted_z_vals, offset)
         C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\bricker_v2-1-0\functions\common\wrappers.py
002 0034:wrapped() ret = fn(*args, **kwargs)
         C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\bricker_v2-1-0\operators\export_ldraw.py
003 0049:execute() self.write_ldraw_file(context)

**Comment by bblanimation** [comment]
Thanks for the report! Fixed this.
