### ISSUE TITLE
Export to ldraw

### ISSUE THREAD

**Issue by amantido** [bblanimation/bricker#84]
Export to Ldraw causes gaps in the model and incorrectly placed stones. See pictures:
![Dragon2](https://user-images.githubusercontent.com/72348680/95018960-f7ddc500-0662-11eb-8fc2-e97ce7633a9c.png)

![Dragon](https://user-images.githubusercontent.com/72348680/95018914-c107af00-0662-11eb-9903-8828297c79fd.png)

When I open the model in the LEGO Digital Designer I get an error message that various bricks were not placed correctly and were removed.
[Dragon.zip](https://github.com/bblanimation/bricker/files/5323434/Dragon.zip)

The model looks correct in the blender:
![DragonBlender](https://user-images.githubusercontent.com/72348680/95019060-9833e980-0663-11eb-8100-0a1b2a248416.png)

**Comment by bblanimation** [comment]
Hi,

Thank you for reporting this issue! Which version of Bricker are you running? This issue should be fixed for version 2.1 and later.

-Christopher

**Comment by amantido** [comment]
Hi Christopher,

I have version 2.1.0. The updater cannot find a newer version.

Best Regards
Frank


Von: Christopher Gearhart <notifications@github.com>
Gesendet: Sonntag, 4. Oktober 2020 19:03
An: bblanimation/bricker <bricker@noreply.github.com>
Cc: amantido <frankmueller1985@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [bblanimation/bricker] Export to ldraw (#84)

Hi,

Thank you for reporting this issue! Which version of Bricker are you running? This issue should be fixed for version 2.1 and later.

-Christopher

**Comment by bblanimation** [comment]
Interesting - thanks for the info. Would you mind uploading the Blend file where you exported this model so that I can get to the bottom of this?

**Comment by amantido** [comment]
Of course. Github don’t accept files over 10MB so I uploaded it to wetransfer.com. Here is he download link:

https://we.tl/t-Qm1JqwFvXR

Best regards
Frank

Von: Christopher Gearhart <notifications@github.com>
Gesendet: Sonntag, 4. Oktober 2020 21:44
An: bblanimation/bricker <bricker@noreply.github.com>
Cc: amantido <frankmueller1985@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [bblanimation/bricker] Export to ldraw (#84)


Interesting - thanks for the info. Would you mind uploading the Blend file where you exported this model so that I can get to the bottom of this?

**Comment by bblanimation** [comment]
Thank you for sending the file over. I've fixed this issue; the fix will be included in the next release of Bricker!
